### ISSUE TITLE
Error after using precompiled binaries

### ISSUE THREAD

**Issue by darrenhakimi** [limneos/MobileMiner#15]
Hi. I dragged the precompiled binaries file into the MobileMiner Group within the Xcode project. I then removed the -lcrypto flag from both the Debug and Releases sections of the Other Linker Flags section in Build Settings. Now, I am getting the attached error. Please let me know what steps need to be taken from here. Thank you!

![screen shot 2018-01-12 at 3 01 33 am](https://user-images.githubusercontent.com/22161961/34865144-98f815ec-f745-11e7-9e9a-9a04efbf0296.png)

**Comment by acexo** [comment]
You are trying to run it for the simulator, don't.

**Comment by darrenhakimi** [comment]
As evident in the screenshot, I have my iPhone selected in the top left corner. Where else do I need to select to run on my iPhone rather than the simulator? Thank you.

**Comment by limneos** [comment]
It appears that minerd.a is not included, since it cannot find its exported symbol "start_mining".
Have you dragged minerd.a into the project?
Have you set -all_load in Other Linker Flags?

**Comment by darrenhakimi** [comment]
Below is a video of the exact steps I take, which cause the error, running on a clean copy of MobileMiner:
https://www.dropbox.com/s/uqtx0275dl1c7v3/MobileMiner%20Linking%20Error.mov?dl=0
Thank you for your feedback.

**Comment by limneos** [comment]
1) Since you're dragging the precompiled binaries in your project, delete those 2 that appear in red (libjansson.a and libcurl.a). You're double-passing them to the linker.
2) You're trying to run arm64 binaries on simulator. These have been compiled for arm64 only. Use a real device.

**Comment by darrenhakimi** [comment]
Below is an updated video. I addressed the two issues mentioned, but the error is still consistent. Thank you:
https://www.dropbox.com/s/llzcmrler8p9gnp/MobileMiner%20Linking%20Error%202.mov?dl=0

**Comment by limneos** [comment]
It seems it cannot find the directory from which you're importing the libraries.
Try copying the 4 libraries to your Desktop, remove the existing ones from your project, and drag those from Desktop in your project.

**Comment by darrenhakimi** [comment]
I deleted the existing files from my project and tried re-adding them from my desktop. Now, I am getting the same error that I initially posted.
![screen shot 2018-01-14 at 4 42 36 am](https://user-images.githubusercontent.com/22161961/34914689-9bad2b3c-f8e5-11e7-90cc-0efceb980181.png)

**Comment by darrenhakimi** [comment]
Nevermind. It worked. I retried it but did exactly as you said. I moved the files to another directory. Then, I deleted them from Xcode. Lastly, I re-added them to Xcode from the new directory. Thank you!!
