### ISSUE TITLE
Developer Donation

### ISSUE THREAD

**Issue by ghost** [limneos/MobileMiner#17]
I can understand if you don't want people to know this but if you are willing can you tell me where the developer donation levels are located in the source code?

**Comment by devingDev** [comment]
what do you mean by this?
Whats the developer donation level you mentioned ?
Is it taking part of the miing?

**Comment by ghost** [comment]
Yes, it auto mines 1% or 36 seconds in one hour for the developer as it says in the disclaimer. FYI I have created a multi-algorithm version of this with that auto mining disabled (I think) that is why I asked the question to be sure I got rid of the right part. <https://github.com/Mrtops/iOS-Miner/releases>
