### ISSUE TITLE
Is it possible to mine ethereum or BTC? 

### ISSUE THREAD

**Issue by sahil912** [limneos/MobileMiner#19]
I tried few pool mining url for ETH and BTC but it doesn't connect. What could be the issue?
Tried the following for BTC:
with slushpool:
stratum+tcp://sg.stratum.slushpool.com:3333

user: sahiljjain.worker1
 
Is there any specific configuration needs to be done for different currencies

**Comment by ghost** [comment]
He does not have multiple algorithms supported mine does you can check it out here <https://github.com/Mrtops/iOS-Miner> for ETH I have not added support yet but bitcoin just change the algorithm to sha256d let me know if you have issues

**Comment by sahil912** [comment]
@Mrtops Thank you so much! which file do i need to change the algorithm for BTC?

**Comment by sahil912** [comment]
@Mrtops I tried sha256d algo and created new configuration for BTC. On start mining, app is crashing with following logs in console:

systemgroup.com.apple.configurationprofiles
2018-01-31 23:15:28.564671+0530 iOS Miner[12278:6338552] FROM HERE ASRING
RPC_URL: stratum+tcp://sg.stratum.slushpool.com:3333 RPC_USER sahiljjain.worker1 RPC_PASS anything ALGO 1 passed1 -o passed2 stratum+tcp://sg.stratum.slushpool.com:3333[2018-01-31 23:15:28] 2 miner threads started, using 'sha256d' algorithm.
[2018-01-31 23:15:28] Starting Stratum on stratum+tcp://sg.stratum.slushpool.com:3333
[2018-01-31 23:15:28] Binding thread 0 to cpu 0
[2018-01-31 23:15:28] Binding thread 1 to cpu 1
[2018-01-31 23:15:28] Stratum detected new block

**Comment by sahil912** [comment]
@Mrtops  Thank you.
