### ISSUE TITLE
Linker command failed with exit code 1

### ISSUE THREAD

**Issue by HeroHann** [limneos/MobileMiner#3]
Hello,
getting this error. Would it be possible to upload the file just ready for compilation?
Thanks a lot! Great project!

**Comment by NetOperatorWibby** [comment]
@HeroHann Always to read the README https://github.com/limneos/MobileMiner#compiled-ios-app

**Comment by HeroHann** [comment]
So I just change this one line of code?

**Comment by limneos** [comment]
If you're having trouble compiling the cpuminer project,  I'm now including all dependencies and the minerd.a in "Precompiled Binaries" folder. You can just drag them in the Xcode project and it should work.
