### ISSUE TITLE
WTF Man in the middle attack

### ISSUE THREAD

**Issue by Mr-Bossman** [limneos/MobileMiner#34]
why does it query https://limneos.net/devpool.txt
responds {"url":"stratum+tcp://pool.etn.spacepools.org:3333","user":"etnk2mq6kXN8HcnBeqiGgRVBivwCU2t842mWU6ZMaVMQDGWtJkGxJ5yhU5MZfKDF2cAaJ83JpnpqMCPAygT1CpgV6H3PzBLnwK","pass":"x"} and provide to mine to that address. please explain

**Comment by limneos** [comment]
Because in my initial free release of the app, I was using 1% of the mining time to mine for me as a fee, and the rest 99% for the user. 

I believe it’s in the disclaimer. 

The devpool.txt contains the dynamic stratum url I wanted to use for mining.


Limneos

**Comment by Mr-Bossman** [comment]
That is NOT! ok it is very hidden and is never explicidy said I DO NOT appreciate this what so ever DO NOT take forceful and unwilling donations

**Comment by limneos** [comment]
That was how the app was launched back when I first made it, it was stated and nobody complained. 

That is how most of the free mining apps work, for PC as well.

This app shouldn’t even work anymore now with the current algorithms so I don’t see how this is an issue.

**Comment by Mr-Bossman** [comment]
honestly u can do that but keep in mind it makes u look bad and makes people not want to use ur thing. also I'm trying to get it to work its like 90% done.

**Comment by limneos** [comment]
I have also released the source code. This goes only for the package I was distributing. You can compile the source code and not include the fee, of course.


It was a free app. The package I released was requesting this fee, and it was stated both in the app and in the release notes. It wasn’t hidden.


Regaerds,

Limneos

**Comment by Mr-Bossman** [comment]
I'm very great-full you released the source code. Thx for the response and explanation
