### ISSUE TITLE
when I compile. it throw out this error

### ISSUE THREAD

**Issue by madist** [limneos/MobileMiner#4]
./configure: line 5688: syntax error near unexpected token `,'
./configure: line 5688: `LIBCURL_CHECK_CONFIG(, 7.15.2, ,'

**Comment by limneos** [comment]
Yeah, this is a bug propagating in all forks from the initial project.
just #comment this line out, from any of the configure, configure.in etc files

**Comment by mooseDev** [comment]
or see instructions to fix issues: [https://www.anintegratedworld.com/to-build-from-source-binary-or-tarball/](https://www.anintegratedworld.com/to-build-from-source-binary-or-tarball/l)
