### ISSUE TITLE
When i try to compile i get this error

### ISSUE THREAD

**Issue by hughandann50th** [limneos/MobileMiner#5]
I don't really know what it means?
<img width="858" alt="screen shot 2017-12-22 at 4 26 42 pm" src="https://user-images.githubusercontent.com/31420840/34312850-fc2e39d2-e734-11e7-8d3c-4be9adafb096.png">

**Comment by limneos** [comment]
have you compiled openssl for iOS? if you have and you have dragged  libcrypto.a into the project, go to Build Settings - Other Flags, and remove the -lcrypto. 

Leave only: -all_load

**Comment by hughandann50th** [comment]
Thanks

**Comment by artemnovichkov** [comment]
I did it, but still have the error

**Comment by limneos** [comment]
If you're having trouble compiling the cpuminer project,  I'm including all dependencies and the minerd.a in Precompiled Binaries folder. You can just drag them in the Xcode project and it should work.
