### ISSUE TITLE
how to compile c file and create minerd.a

### ISSUE THREAD

**Issue by zhengyanfeng** [limneos/MobileMiner#7]
Hi

I clone this project into my mac, I switch to folder MobileMiner in terminal

I follow the Instructions "Compile c files (cpuminer project files) for target arm64"

then I type clang cpu-miner.c in terminal, there is a error : "fatal error: 'cpuminer-config.h' file not found"

anyone know how to create a "minerd.a" library

**Comment by limneos** [comment]
If you're having trouble compiling the cpuminer project,  I'm including all dependencies and the minerd.a in Precompiled Binaries folder. You can just drag them in the Xcode project and it should work.

**Comment by zhengyanfeng** [comment]
OK, I got this, thanks a lot

**Comment by gmyanfeng** [comment]
OK, I got this, thanks a lot
