### ISSUE TITLE
library not found for -ljansson

### ISSUE THREAD

**Issue by n00bax** [limneos/MobileMiner#8]
I've compiled and installed jansson but how do I add jansson library to xcode?

**Comment by limneos** [comment]
You just drag the generated libjansson.a into the project.
Alternatively, I'm including all dependencies and the minerd.a in Precompiled Binaries folder.

**Comment by X-43A** [comment]
The problem is that I don't have the libjansson.a file.
I'll look into that Procompiled Binaries folder, thanks
